# Encode all certificate PDFs as base64 into a single JS file (pdfdata.js)
# PDF.js can then load from the embedded data without needing fetch() — works on file:// too.

$projectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$imagesDir   = Join-Path $projectRoot 'images'
$outFile     = Join-Path $projectRoot 'pdfdata.js'

$allPdfs = Get-ChildItem -LiteralPath $imagesDir -Filter '*.pdf' -File
$used = @{}
function Pick-One($pattern) {
    foreach ($p in $allPdfs) {
        if (-not $used[$p.FullName] -and $p.Name -like $pattern) {
            $used[$p.FullName] = $true; return $p
        }
    }
    return $null
}

$jobs = @(
    @{ Id = 'cert-oeko';        Pattern = '21.0.61626*' }
    @{ Id = 'cert-rsl';         Pattern = '*ChemCheck*' }
    @{ Id = 'cert-quality';     Pattern = '*-Q*.pdf' }
    @{ Id = 'cert-environment'; Pattern = '*-E*.pdf' }
)

$entries = New-Object System.Collections.ArrayList
foreach ($j in $jobs) {
    $hit = Pick-One $j.Pattern
    if (-not $hit) { Write-Warning "No match: $($j.Pattern)"; continue }
    Write-Host "Encoding: $($hit.Name) -> $($j.Id) ($([math]::Round($hit.Length/1KB,1)) KB)"
    $bytes = [System.IO.File]::ReadAllBytes($hit.FullName)
    $b64 = [Convert]::ToBase64String($bytes)
    [void]$entries.Add(@{ Id = $j.Id; Source = $hit.Name; Base64 = $b64 })
}

# Remaining PDFs (Chinese-named SME honor certs), deterministic by length desc
$remaining = $allPdfs | Where-Object { -not $used[$_.FullName] } | Sort-Object Length -Descending
$honorIds = @('cert-honor-1', 'cert-honor-2')
for ($i = 0; $i -lt [Math]::Min($remaining.Count, $honorIds.Count); $i++) {
    $hit = $remaining[$i]
    Write-Host "Encoding: $($hit.Name) -> $($honorIds[$i]) ($([math]::Round($hit.Length/1KB,1)) KB)"
    $bytes = [System.IO.File]::ReadAllBytes($hit.FullName)
    $b64 = [Convert]::ToBase64String($bytes)
    [void]$entries.Add(@{ Id = $honorIds[$i]; Source = $hit.Name; Base64 = $b64 })
}

# Build JS output
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// Auto-generated by build-pdfdata.ps1. Do not edit manually.")
[void]$sb.AppendLine("// Embeds certificate PDFs as base64 so PDF.js works without an HTTP server (file:// safe).")
[void]$sb.AppendLine("window.PDF_DATA = {")
for ($i = 0; $i -lt $entries.Count; $i++) {
    $e = $entries[$i]
    $comma = if ($i -lt $entries.Count - 1) { ',' } else { '' }
    [void]$sb.AppendLine("  // source: $($e.Source)")
    [void]$sb.AppendLine("  '$($e.Id)': '$($e.Base64)'$comma")
}
[void]$sb.AppendLine("};")

[System.IO.File]::WriteAllText($outFile, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))

$outSize = [math]::Round((Get-Item $outFile).Length / 1MB, 2)
Write-Host "`nWrote: $outFile ($outSize MB)"
Write-Host "Entries: $($entries.Count)"
$entries | ForEach-Object { Write-Host "  $($_.Id) <- $($_.Source)" }
